"""Agent Runtime type definitions.

Mirrors Kuse Cowork's AgentEvent + Plan types, adapted for async Python.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class AgentEventType(str, Enum):
    """Events emitted during agent execution."""

    PLAN = "plan"  # LLM generated a plan
    STEP_START = "step_start"  # Starting a step
    STEP_DONE = "step_done"  # Step completed
    TOOL_CALL = "tool_call"  # Calling a tool
    TOOL_RESULT = "tool_result"  # Tool returned result
    TEXT = "text"  # Intermediate text output
    ERROR = "error"  # Error occurred
    USER_ACTION = "user_action"  # User approved/rejected/modified
    COMPLETE = "complete"  # Agent finished


class RunStatus(str, Enum):
    """Agent run lifecycle states."""

    PENDING = "pending"
    PLANNING = "planning"
    AWAITING_APPROVAL = "awaiting_approval"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


@dataclass
class PlanStep:
    """A single step in the agent's plan."""

    id: int
    description: str
    tool: str | None = None  # tool name to invoke
    args: dict[str, Any] = field(default_factory=dict)
    status: str = "pending"  # pending | running | done | failed | skipped


@dataclass
class AgentPlan:
    """Plan generated by the LLM before execution."""

    goal: str
    steps: list[PlanStep]
    estimated_sections: int = 0


@dataclass
class AgentEvent:
    """An event emitted during agent execution, persisted to agent_logs."""

    event_type: AgentEventType
    message: str
    step_number: int | None = None
    data: dict[str, Any] | None = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_ws_dict(self) -> dict[str, Any]:
        """Serialize for WebSocket transmission."""
        return {
            "event_type": self.event_type.value,
            "message": self.message,
            "step_number": self.step_number,
            "data": self.data,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class ToolDefinition:
    """A tool available to the agent."""

    name: str
    description: str
    parameters: dict[str, Any] = field(default_factory=dict)


@dataclass
class ToolResult:
    """Result returned by a tool execution."""

    success: bool
    output: str
    data: dict[str, Any] | None = None
